"""add_user_is_pro_and_token_usage_table

Revision ID: 369f827eaf12
Revises: a1b2c3d4e5f6
Create Date: 2026-05-31 22:52:44.354848
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "369f827eaf12"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_usage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("model_used", sa.String(length=100), nullable=False),
        sa.Column("request_type", sa.String(length=50), nullable=False),
        sa.Column(
            "performance_mode",
            sa.String(length=20),
            server_default="high",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_user_activity_user_date"), table_name="user_activity")
    op.add_column(
        "users",
        sa.Column("is_pro", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_pro")
    op.create_index(
        op.f("ix_user_activity_user_date"),
        "user_activity",
        ["user_id", "activity_date"],
        unique=False,
    )
    op.drop_table("token_usage")
    # ### end Alembic commands ###
