"""combined_auth_and_summaries

Revision ID: 372dee4b2ff1
Revises: 369f827eaf12
Create Date: 2026-06-04 06:43:40.954976
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "372dee4b2ff1"
down_revision: str | None = "369f827eaf12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "summary_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("doc_id", sa.UUID(), nullable=True),
        sa.Column("topic", sa.String(length=500), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("format", sa.String(length=50), nullable=False),
        sa.Column("structured", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("context_sufficient", sa.Boolean(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "performance_mode",
            sa.String(length=20),
            server_default="high",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["doc_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_summary_history_created_at"),
        "summary_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_summary_history_doc_id"), "summary_history", ["doc_id"], unique=False
    )
    op.create_index(
        op.f("ix_summary_history_user_id"), "summary_history", ["user_id"], unique=False
    )
    op.add_column(
        "chat_history",
        sa.Column(
            "performance_mode",
            sa.String(length=20),
            server_default="high",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_chat_history_doc_id"), "chat_history", ["doc_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_history_user_id"), "chat_history", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_user_id"), "documents", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_answers_session_id"), "quiz_answers", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_sessions_doc_id"), "quiz_sessions", ["doc_id"], unique=False
    )
    op.create_index(
        op.f("ix_quiz_sessions_user_id"), "quiz_sessions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_token_usage_created_at"), "token_usage", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_token_usage_user_id"), "token_usage", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_activity_user_id"), "user_activity", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_activity_user_id"), table_name="user_activity")
    op.drop_index(op.f("ix_token_usage_user_id"), table_name="token_usage")
    op.drop_index(op.f("ix_token_usage_created_at"), table_name="token_usage")
    op.drop_index(op.f("ix_quiz_sessions_user_id"), table_name="quiz_sessions")
    op.drop_index(op.f("ix_quiz_sessions_doc_id"), table_name="quiz_sessions")
    op.drop_index(op.f("ix_quiz_answers_session_id"), table_name="quiz_answers")
    op.drop_index(op.f("ix_documents_user_id"), table_name="documents")
    op.drop_index(op.f("ix_chat_history_user_id"), table_name="chat_history")
    op.drop_index(op.f("ix_chat_history_doc_id"), table_name="chat_history")
    op.drop_column("chat_history", "performance_mode")
    op.drop_index(op.f("ix_summary_history_user_id"), table_name="summary_history")
    op.drop_index(op.f("ix_summary_history_doc_id"), table_name="summary_history")
    op.drop_index(op.f("ix_summary_history_created_at"), table_name="summary_history")
    op.drop_table("summary_history")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
