import type { Metadata } from "next";
import { LegalLayout, LegalSection } from "../LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service — StudyMate",
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" updated="June 2026">
      <p>
        These terms govern your use of StudyMate, an academic study companion that turns your own PDF
        lecture notes into AI-powered chat, summaries, and quizzes. By creating an account or using
        the service, you agree to the terms below.
      </p>

      <LegalSection heading="1. Eligibility & Accounts">
        <p>
          You are responsible for the accuracy of your registration details and for keeping your
          login credentials secure. You may not share your account or use another person&rsquo;s
          account without permission.
        </p>
      </LegalSection>

      <LegalSection heading="2. Acceptable Use">
        <ul className="list-disc pl-5 flex flex-col gap-1.5">
          <li>Upload only PDF documents you have the right to use for your own study.</li>
          <li>
            Do not upload unlawful, infringing, or harmful content, and do not attempt to disrupt,
            reverse-engineer, or overload the service.
          </li>
          <li>
            Do not use the service to generate content that violates the rights of others or any
            applicable law or institutional policy on academic integrity.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="3. Your Content">
        <p>
          You retain ownership of the documents you upload. You grant StudyMate a limited license to
          process them — extracting text, creating embeddings, retrieving excerpts, and generating
          responses — solely to provide the service to you. Deleting a document removes its metadata
          and indexed vectors from our systems.
        </p>
      </LegalSection>

      <LegalSection heading="4. AI Output Disclaimer">
        <p>
          Answers, summaries, and quiz questions are generated by an AI model grounded in your
          retrieved content. They may be incomplete or incorrect and are provided for study purposes
          only. They are <strong className="text-white">not</strong> authoritative academic advice —
          always verify against your original sources. StudyMate is not liable for decisions made in
          reliance on AI output.
        </p>
      </LegalSection>

      <LegalSection heading="5. Usage Limits">
        <p>
          To keep the service available and manage costs, generation is subject to a daily token
          limit based on your plan tier. Exceeding the limit pauses generation until the daily reset
          at midnight UTC.
        </p>
      </LegalSection>

      <LegalSection heading="6. Availability & Changes">
        <p>
          As an academic project, the service is provided &ldquo;as is&rdquo; without warranties of
          uptime or fitness for a particular purpose. We may modify, suspend, or discontinue features
          at any time. Continued use after changes to these terms constitutes acceptance of them.
        </p>
      </LegalSection>

      <LegalSection heading="7. Termination">
        <p>
          You may stop using the service and request account deletion at any time. We may suspend or
          terminate accounts that violate these terms.
        </p>
      </LegalSection>

      <LegalSection heading="8. Contact">
        <p>
          For questions about these terms, contact the project maintainer, Ekwem Kamsiyochukwu
          Fredrick, Federal University of Technology, Owerri.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
